### ISSUE TITLE
What license governs jquery-linkify?

### ISSUE THREAD

**Issue by johnmhoran** [uudashr/jquery-linkify#12]
Hi @uudashr .  I've noticed that you have licensed several other projects under the MIT License but cannot find any licensing information for `jquery-linkify`.  What license applies to this project?  Thanks very much.

**Comment by uudashr** [comment]
I might put Apache License 2.0

**Comment by johnmhoran** [comment]
Thank you @uudashr .

**Comment by johnmhoran** [comment]
@uudashr  Following up on our earlier chat, we're interested in using `jquery-linkify` but need a clearly-defined license to do so, and as it happens we use Apache 2.0 ourselves.  Would you agree to license the package under Apache 2.0?

**Comment by uudashr** [comment]
Hi, I just added the license to the master. I hope that helps you.

I'll close this ticket, feel free to reopen if you have any concerns.

**Comment by johnmhoran** [comment]
That's great -- thank you, @uudashr
